config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end
  # ユーザー用 / コントローラーの指定と余分なルーティングの削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用 / コントローラーの指定と余分なルーティングの削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログインの記述
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング設定
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root to: "home#top"
    # ワード検索用のルーティング↓↓
    get "search" => "searches#search"
    # Userの退会用ルーティング↓↓
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね機能のルーティング↓↓
      # params[:id]不要なため、resourceは単数系で。
      resource :favorites, only: [:create, :destroy]
      # コメント機能のルーティング↓↓
      resources :post_comments, only: [:create, :destroy]
    end
    # 通知機能
    resources :notifications, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  
  # 投稿する際に、空欄を禁止する。
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "投稿が成功しました。"
      redirect_to request.referer
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end


  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container pt-5 pb-5">
  <div class="row">
    <!--左側のページ-->
    <div class="col-md-2">
      <button type="button" class="btn btn-success rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2>Edit</h2>
      </button>
    </div>
    <!--右側のページ-->
    <div class="col-md-9 offset-md-1 py-4">
       <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
        <table>
          <tr>
            <th class="pt-4"><%= f.label :ジャンル変更 %></th>
          </tr>
          <tr>
            <td class="py-2"><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td class="pt-2 pb-4"><%= f.submit '変更を保存', class: 'btn btn-info' %></td>
          </tr>
        </table>
      <% end %>
      <div class="mt-3">
         <%= link_to 'Back', :back %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div>
<% if @genre.errors.any? %>
  <%= @genre.errors.count %> 件のエラーが発生しました。
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div class="container pt-5 pb-5">
  <div class="row">
    <!--左側のページ-->
    <div class="col-md-2">
      <button type="button" class="btn btn-success rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2>Genre</h2>
      </button>
      <!--ジャンル新規作成フォーム-->
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <table class="py-3">
        <tr>
          <td class="pt-3 text-right">New Genre</td>
        </tr>
        <tr>
          <td class="py-2"><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td class="text-right"><%= f.submit '追加', class: "btn btn-success" %></td>
        </tr>
      </table>
      <% end %>
    </div>
    <!--右側のページ-->
    <div class="col-md-9 offset-md-1 py-4">
      <table class="table">
        <tr>
          <th>ジャンル名</th>
          <th>登録件数</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
        <% @genres.each do |genre| %>
        <tr>
          <td>
            <%= link_to genre_path(genre.id), class: "text-decoration-none text-info font-weight-bold" do %>
              <% genre.name %>
            <% end %>
          </td>
          <td><%= genre.posts.count %> 件</td>
          <td>
            <%= link_to edit_admin_genre_path(genre.id) do %>
              <i class="fas fa-edit" style="color: #06982b;"></i>
            <% end %>
          </td>
          <td>
            <%= link_to admin_genre_path(genre.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
              <i class="fas fa-trash-alt" style="color: #d2040f;"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>