config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end
  # ユーザー用 / コントローラーの指定と余分なルーティングの削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用 / コントローラーの指定と余分なルーティングの削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログインの記述
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング設定
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root to: "home#top"
    # ワード検索用のルーティング↓↓
    get "search" => "searches#search"
    # Userの退会用ルーティング↓↓
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね機能のルーティング↓↓
      # params[:id]不要なため、resourceは単数系で。
      resource :favorites, only: [:create, :destroy]
      # コメント機能のルーティング↓↓
      resources :post_comments, only: [:create, :destroy]
    end
    # 通知機能
    resources :notifications, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :genre
  has_many :notifications, dependent: :destroy

  # 投稿時に画像がない場合の処理
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  # 投稿する際に、空欄を禁止する。
  validates :title, presence: true
  validates :body, presence: true

  # いいね機能
  # ユーザーIDがFavaritedテーブル内に存在するか調べる記述
  # 存在していればtrue、なければfalseで返す。
  # 管理者でログインしている場合にエラーが出るのでif文で条件追記。
  def favorited_by?(user)
    # userログインをしているかどうかの判断
    if user.present?
      favorites.exists?(user_id: user.id)
    else
      # userログインしていない場合は無条件にfalseを返します。
      false
    end
  end

  # コメント機能
  # コメントしている場合、一覧でアイコンを変えるための記述
  def comment_by?(user)
    if user.present?
      post_comments.exists?(user_id: user.id)
    else
      false
    end
  end

  # ワード検索用の記述
  def self.search(word)
    Post.where(['title LIKE(?) OR body LIKE(?)', "%#{word}%", "%#{word}%"])
  end

  # 通知機能（いいね）
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    # いいねボタン連打した時とかに、押した数だけ通知が行かないようにレコードのチェックを行う。
    # ？はプレースホルダ。「？」を指定した値で置き換えることができる
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # 通知機能（コメント）
  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, post_comment_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user.id, id, 'post_comment'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user.id,
        action: 'post_comment'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container pt-5 pb-5">
  <div class="row">
    <!--左側のページ-->
    <div class="col-md-2">
      <button type="button" class="btn btn-warning rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2>Posts</h2>
      </button>
      <div class="py-5 text-right">
        コメント編集は<br>
        <%= link_to "こちら", admin_post_comments_path, class: "text-decoration-none text-info font-weight-bold" %>
      </div>
    </div>
    <!--右側のページ-->
    <div class="col-md-9 offset-md-1 py-4">
      <table class="table">
        <tr>
          <th>登録日</th>
          <th>タイトル</th>
          <th>ユーザー名</th>
          <th>削除</th>
        </tr>
        <% @posts.each do |post| %>
        <tr>
          <th><%= post.user.created_at.strftime('%Y/%m/%d') %></th>
          <th class="text-truncate" style="max-width: 250px;">
            <%= link_to "#{post.title}", post_path(post.id), class: "text-decoration-none text-info font-weight-bold" %>
          </th>
          <th><%= post.user.name %></th>
          <th>
            <%= link_to admin_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
              <i class="fas fa-trash-alt" style="color: #d2040f;"></i>
            <% end %>
          </th>
        </tr>
        <% end %>
      </table>
      <div>
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>