config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end
  # ユーザー用 / コントローラーの指定と余分なルーティングの削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用 / コントローラーの指定と余分なルーティングの削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログインの記述
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング設定
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root to: "home#top"
    # ワード検索用のルーティング↓↓
    get "search" => "searches#search"
    # Userの退会用ルーティング↓↓
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね機能のルーティング↓↓
      # params[:id]不要なため、resourceは単数系で。
      resource :favorites, only: [:create, :destroy]
      # コメント機能のルーティング↓↓
      resources :post_comments, only: [:create, :destroy]
    end
    # 通知機能
    resources :notifications, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  # フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロー一覧表示のための記述
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 通知機能。activeは自分からの通知、passiveは相手からの通知。
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # ゲストログインのユーザー設定
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # プロフィール画像の設定
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_profile.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "You have updated customer_info successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container pt-5 pb-5">
  <div class="row">
    <!--左側のページ-->
    <div class="col-md-2">
      <button type="button" class="btn btn-info rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2>Usres<br>edit</h2>
      </button>
    </div>
    <!--右側のページ-->
    <div class="col-md-9 offset-md-1 py-4">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch  do |f| %>
      <table>
        <tr>
          <th class="p-3">登録日</th>
          <td class="p-3"><%= @user.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th class="p-3">ユーザー名</th>
          <td class="p-3"><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th class="p-3">メールアドレス</th>
          <td class="p-3"><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th class="p-3">ステータス</th>
          <td class="p-3">
            <%= f.radio_button :is_deleted, :false, checked: true %>
            <%= f.label :is_deleted, '有効　', {value: :false} %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, '退会', {value: :true} %>
          </td>
        </tr>
        <tr>
          <th class="p-3"><%= f.submit '変更を保存', class: 'btn btn-success' %></th>
          <th class="p-3"></th>
        </tr>
      </table>
      <% end %>
      <div class="m-3">
         <%= link_to 'Back', :back %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container pt-5 pb-5">
  <div class="row">
    <!--左側のページ-->
    <div class="col-md-2">
      <button type="button" class="btn btn-info rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2>Usres</h2>
      </button>
    </div>
    <!--右側のページ-->
    <div class="col-md-9 offset-md-1 py-4">
      <table class="table">
        <tr>
          <th>登録日</th>
          <th>ユーザー名</th>
          <th>ステータス</th>
          <th>編集ページ</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <th><%= user.created_at.strftime('%Y/%m/%d') %></th>
          <th><%= user.name %></th>
          <th>
            <% if user.is_deleted == false %>
            <span class="status-validity">有効</span>
            <% else %>
            <span class="status-invalid">退会</span>
            <% end %></th>
          <th><%= link_to "詳細", edit_admin_user_path(user.id), class: "text-decoration-none text-info font-weight-bold" %></th>
        </tr>
        <% end %>
      </table>
      <div>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>