config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end
  # ユーザー用 / コントローラーの指定と余分なルーティングの削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用 / コントローラーの指定と余分なルーティングの削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログインの記述
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング設定
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root to: "home#top"
    # ワード検索用のルーティング↓↓
    get "search" => "searches#search"
    # Userの退会用ルーティング↓↓
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね機能のルーティング↓↓
      # params[:id]不要なため、resourceは単数系で。
      resource :favorites, only: [:create, :destroy]
      # コメント機能のルーティング↓↓
      resources :post_comments, only: [:create, :destroy]
    end
    # 通知機能
    resources :notifications, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row justify-content-center">
    <%= link_to new_admin_session_path, class: 'admin-login' do %>
      <i class="fas fa-paw"></i><% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!--ロゴ-->
          <a class="navbar-brand" href="/"><i class="fas fa-paw"></i><span class= "header-text"> CatJournal</span></a>
        <!--メニュー-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <!--管理者がログインしている際に表示させるヘッダー-->
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_users_path, class: 'nav-link' do %>
                <i class="fas fa-users"></i> User<% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_posts_path, class: 'nav-link' do %>
                <i class="fas fa-list"></i> Journal<% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_genres_path, class: 'nav-link' do %>
                <i class="fas fa-tree"></i>Genre<% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link' do %>
                <i class="fas fa-sign-out-alt"></i> Log out<% end %>
              </li>
            <!--ユーザーでログインしている際に表示させるヘッダー-->
            <% elsif user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link' do %>
                <i class="fas fa-heart"></i> My page<% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link' do %>
                <i class="fas fa-users"></i> User<% end %>
              </li>
              <li class="nav-item">
                <%= link_to posts_path, class: 'nav-link' do %>
                <i class="fas fa-list"></i> Journals<% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                <i class="fas fa-sign-out-alt"></i> Log out<% end %>
              </li>
              <li class="nav-item">
                <!--通知機能-->
                <%= link_to notifications_path, class: 'nav-link' do %>
                  <% if unchecked_notifications.any? %>
                    <i class="fas fa-bell" style="color: #fdc11c;"></i>
                  <% else %>
                    <i class="far fa-bell"></i>
                  <% end %>
                <% end %>
              </li>
            <!--ログインしていない場合に表示させるヘッダー-->
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link' do %>
                <i class="fas fa-home"></i> Home<% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_guest_sign_in_path, class: 'nav-link', method: :post do %>
                <i class="fas fa-unlock-alt"></i> Guest<% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link' do %>
                <i class="fas fa-user-plus"></i> Sign up<% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link' do %>
                <i class="fas fa-sign-in-alt"></i> Log in<% end %>
              </li>
            <% end %>
          </div>

    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cat Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="shadow-sm">
    <%= render "layouts/header" %>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer class="fixed-bottom">
    <%= render "layouts/footer" %>
  </footer>

</html>